version: "3"

services:
  nginx:
    image: nginx:latest
    volumes:
      - ./:/var/www
      - ./_docker/nginx/conf.d/:/etc/nginx/conf.d/
    ports:
      - 8876:80
    depends_on:
      - app # Это правило для nginx чтобы он запускался только после того как запустится `php`
    networks:
      - domovkin

  app: 
    image: php:8.2-fpm
    build: 
      context: .
      dockerfile: _docker/app/DockerFile
    volumes:
      - ./:/var/www
      - ./storage:/var/www/storage
    container_name: app_domovkin
    depends_on:
      - db
    networks:
      - domovkin

  db:
    image: mysql:8.0
    restart: always
    volumes:
      - ./tmp/db:/var/lib/mysql
    environment:
      MYSQL_DATABASE: domovkin
      MYSQL_ROOT_PASSWORD: root
    
    ports:
      - 8102:3306
    command: --character-set-server=utf8 --collation-server=utf8_unicode_ci
    networks:
        - domovkin

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_domovkin
    environment:
        PMA_HOST: db
        PMA_USER: root
        PMA_PASSWORD: root
        UPLOAD_LIMIT: 932057252
    ports:
        - "8080:80"
    networks:
        - domovkin

networks:
  domovkin:
      driver: bridge
      name: domovkin